#!/usr/bin/env tsx
/**
 * Regenerate `games/server-registry.ts` and sync `@games/*` deps in the root
 * `package.json` from the filesystem.
 *
 * Scans `games/<id>/` directories, skips `_template` and any folder missing
 * `logic.ts` + `shared.ts` (partial / scaffolded games), then:
 *   1. Writes a clean `games/server-registry.ts` with static ESM imports.
 *   2. Updates root `package.json` so every discovered game appears as a
 *      `workspace:*` dependency. Root-level deps are required because the
 *      server resolves `@games/*` via Node's bare-specifier lookup — deleting
 *      them silently breaks `pnpm dev`.
 *
 * Usage: `pnpm gen:registry` — run whenever you add, remove, or rename a game.
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const gamesDir = resolve(root, 'games');
const outFile = join(gamesDir, 'server-registry.ts');
const rootPkgFile = join(root, 'package.json');

interface Entry {
  dir: string;
  id: string;
  varBase: string;
  pkgName: string;
}

function toVar(dirName: string): string {
  return dirName.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
}

const entries: Entry[] = [];
for (const ent of readdirSync(gamesDir, { withFileTypes: true })) {
  if (!ent.isDirectory()) continue;
  if (ent.name.startsWith('_') || ent.name.startsWith('.')) continue;
  const dir = join(gamesDir, ent.name);
  const sharedFile = join(dir, 'shared.ts');
  const logicFile = join(dir, 'logic.ts');
  if (!existsSync(sharedFile) || !existsSync(logicFile)) {
    // By this point the dir does NOT start with `_` (filtered above), so
    // missing shared.ts/logic.ts almost always means an incomplete game.
    // The hint nudges the user toward the `_name` convention for deliberate
    // placeholders like half-designed games.
    const missing = !existsSync(sharedFile) ? 'shared.ts' : 'logic.ts';
    console.warn(
      `[gen-registry] skipping "${ent.name}" — missing ${missing}\n` +
        `  hint: if this is a placeholder, rename to _${ent.name} to silence`,
    );
    continue;
  }
  const shared = (await import(pathToFileURL(sharedFile).href)) as { meta?: { id?: string } };
  const id = shared.meta?.id;
  if (!id) {
    console.warn(`[gen-registry] skipping "${ent.name}" — shared.ts has no meta.id`);
    continue;
  }
  entries.push({ dir: ent.name, id, varBase: toVar(ent.name), pkgName: `@games/${ent.name}` });
}
entries.sort((a, b) => a.dir.localeCompare(b.dir));

// 1. Write games/server-registry.ts
const header =
  '// AUTO-GENERATED by scripts/gen-registry.ts. Do not edit manually.\n// Run `pnpm gen:registry` to refresh after adding or renaming a game.';
const importLines = entries.flatMap((e) => [
  `import { logic as ${e.varBase}Logic } from '@games/${e.dir}/logic';`,
  `import { meta as ${e.varBase}Meta } from '@games/${e.dir}/shared';`,
]);
const body = `export const serverRegistry: Record<string, ServerGamePlugin> = {\n${entries
  .map((e) => `  [${e.varBase}Meta.id]: { meta: ${e.varBase}Meta, logic: ${e.varBase}Logic },`)
  .join('\n')}\n};\n`;

const content = [
  header,
  '',
  ...importLines,
  "import type { ServerGamePlugin } from '@repo/shared';",
  '',
  body,
].join('\n');
writeFileSync(outFile, content);
console.log(
  `[gen-registry] wrote ${relative(root, outFile)} with ${entries.length} games: ${entries
    .map((e) => e.id)
    .join(', ')}`,
);

// 2. Sync root package.json deps
const pkg = JSON.parse(readFileSync(rootPkgFile, 'utf-8')) as {
  dependencies?: Record<string, string>;
  [key: string]: unknown;
};
const deps = pkg.dependencies ?? {};
const currentGameDeps = Object.keys(deps).filter((k) => k.startsWith('@games/'));
const targetGameDeps = entries.map((e) => e.pkgName).sort();

const stale = currentGameDeps.filter((d) => !targetGameDeps.includes(d));
const missing = targetGameDeps.filter((d) => !currentGameDeps.includes(d));

if (stale.length === 0 && missing.length === 0) {
  console.log('[gen-registry] root package.json @games/* deps already in sync');
} else {
  // Sorted @games/* entries first (matching the existing file convention),
  // then other deps in their original order. This keeps diffs minimal when
  // only game deps change.
  const nonGameOrder = Object.keys(deps).filter((k) => !k.startsWith('@games/'));
  const nonGameDeps: Record<string, string> = {};
  for (const k of nonGameOrder) {
    const v = deps[k];
    if (v !== undefined) nonGameDeps[k] = v;
  }
  const gameDepsObj: Record<string, string> = {};
  for (const name of targetGameDeps) gameDepsObj[name] = 'workspace:*';
  pkg.dependencies = { ...gameDepsObj, ...nonGameDeps };
  writeFileSync(rootPkgFile, `${JSON.stringify(pkg, null, 2)}\n`);
  if (stale.length) console.log(`[gen-registry] removed stale deps: ${stale.join(', ')}`);
  if (missing.length) console.log(`[gen-registry] added deps: ${missing.join(', ')}`);
  console.log('[gen-registry] remember to run `pnpm install` to refresh node_modules symlinks');
}

// 3. Generate SVG icon manifest so GameIcon can detect which game-icons
// exist at build time. `public/` is not part of Vite's module graph, so
// import.meta.glob cannot see SVGs there. A generated TS file does the job.
const iconsDir = resolve(root, 'packages/client/public/game-icons');
const iconsOutFile = resolve(root, 'packages/client/src/generated/game-icons.ts');
const svgNames = existsSync(iconsDir)
  ? readdirSync(iconsDir)
      .filter((f) => f.endsWith('.svg'))
      .map((f) => f.replace(/\.svg$/, ''))
      .sort()
  : [];
mkdirSync(dirname(iconsOutFile), { recursive: true });
const svgLines = svgNames.map((n) => `  '${n}',`).join('\n');
const svgTrailingNewline = svgNames.length ? '\n' : '';
const iconsContent = `// AUTO-GENERATED by scripts/gen-registry.ts. Do not edit manually.
// Run \`pnpm gen:registry\` after adding or removing SVGs under
// packages/client/public/game-icons/.
export const SVG_ICON_NAMES = new Set<string>([
${svgLines}${svgTrailingNewline}]);
`;
writeFileSync(iconsOutFile, iconsContent);
console.log(`[gen-registry] wrote ${relative(root, iconsOutFile)} with ${svgNames.length} icons`);
